spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 2h
client:
  keystore: src/main/resources/keystore-production.jks
  truststore: src/main/resources/truststore-production.jks

mail-gun:
  shouldCC: true
  
intercom-chat-app-id: dje5ebi4
 
mnit-filenet:
  enabled: true
