spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 10m

intercom-chat-app-id: mmxasuhx
         
mnit-filenet:
  enabled: false

demo: true
